# docker-compose.dev.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '8400:3000'
    volumes:
      - ./frontend:/app
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
