# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8400:3000'
    # environment:
    #   - NODE_ENV=production
    # depends_on:
    #   - backend
    networks:
      - app-network

  # backend:
  #   image: your-backend-image
  #   # Configure your backend service here
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
